name: Process HDI File

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 全履歴を取得して、git pull --rebase --autostash が正常に動作するようにする

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip gzip kpartx

      - name: Unzip disk.zip Archive
        run: |
          unzip disk.zip -d extracted
          if [ -f extracted/disk.hdi ]; then
              cp extracted/disk.hdi .
          else
              echo "disk.hdi not found in the extracted archive!"
              exit 1
          fi

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python Dependencies
        run: pip install pyfatfs

      - name: Process HDI File
        run: python process_hdi.py

      - name: Upload modified HDI as artifact
        uses: actions/upload-artifact@v4
        with:
          name: disk_modified_compressed.hdi.zip
          path: disk_modified_compressed.hdi.zip

      - name: Commit and Push ZIP to Repository
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git pull --rebase --autostash origin main
          git add disk_modified_compressed.hdi.zip
          git commit -m "Add updated disk_modified_compressed.hdi.zip" || echo "No changes to commit."
          git push origin main
